name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.1"]

    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true